dataset:
  num_label: 5

pre_train_model:
  wav2vec2_base: "facebook/wav2vec2-base"
  wav2vec2_cr: "alianurrahman/wav2vec2_cr"
  wav2vec2_cr_rd: "alianurrahman/wav2vec2_cr_rd"
  wav2vec2_cr_rd_sv: "alianurrahman/wav2vec2_cr_rd_sv"
  wav2vec2_cr_rd_sv_ts: "alianurrahman/wav2vec2_cr_rd_sv_ts"

training_arguments:
  output_dir: "wav2vec2-base-indonesian-speech-emotion-recognition"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  logging_strategy: "epoch"
  learning_rate: 5.0e-5 #5e-5
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 2
  gradient_checkpointing: True
  num_train_epochs: 20
  seed: 42
  run_name: "wav2vec2_idser_nomaxlength"
  #  warmup_ratio: 0.1
  report_to: "wandb"
  #  load_best_model_at_end: True
  metric_for_best_model: "accuracy"
  #  push_to_hub: True
