# customizing the downloaded audio for our needs
ydl_opts:
  format: "bestaudio/best"
  audio-format: "wav"
  outtmpl: "audio.wav"
  noplaylist: True

links_file: "/content/links.txt" # File containing links to YouTube videos
categories: ['angry', 'disgust', 'fear', 'happy', 'neutral', 'ps', 'sad'] # Emotion Labels

etl:
  raw_data_file: "data/winequality.csv"
  processed_path: "data"
  test_size: 0.2
  random_state: 42

train:
  processed_train: "data/train.csv"
  ensemble_model: "RandomForestClassifier"
  model_config: {n_estimators: 100, random_state: 42}
  model_path: "model/rf_model.pkl"

predict:
  model_path: "model/rf_model.pkl"
  processed_test: "data/test.csv"
  predicted_file: "data/predict.csv"
  export_result: True
